# Generated by Django 4.0.7 on 2023-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.CharField(choices=[('Matutino', 'Morning'), ('Vespertino', 'Afternoon'), ('Noturno', 'Night'), ('Não informado', 'Default')], default='Não informado', max_length=50),
        ),
    ]
