# Generated by Django 4.0.7 on 2023-06-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shift',
        ),
    ]
