# Generated by Django 4.0.7 on 2023-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
